### ISSUE TITLE
大牛，遇到个问题。如果处理长视频，例如1080P 一小时 1G的MP4视频，长时间卡在success, frame = video.read()

### ISSUE THREAD

**Issue by luul11** [lxulxu/WatermarkRemover#3]
处理长视频，一直卡在success, frame = video.read()。这部分CV的读取能否优化，或者是否有bug。因为一直没有输出，所以很容易担心问题

**Comment by lxulxu** [comment]
读取视频部分代码已经重构会显示信息，也增加了进度条显示处理视频进度。
