### ISSUE TITLE
安装包时显示病毒

### ISSUE THREAD

**Issue by xiaolongww** [lxulxu/WatermarkRemover#7]
![image](https://github.com/lxulxu/WatermarkRemover/assets/86103538/021f6f9b-1457-43c2-9b51-3019646b0baa)
执行pip install -r requirements.txt显示

**Comment by lxulxu** [comment]
关闭防毒软件
参考https://stackoverflow.com/questions/73639396/getting-error-while-installing-python-package-scrapy
https://velog.io/@csu5216/condaError-ERROR-Could-not-install-packages-due-to-an-OSError-WinError-225

**Comment by xiaolongww** [comment]
解决了感谢，我把火绒退了，使用火绒文件粉碎reason cybersecurity即可
